### ISSUE TITLE
TeamRPI Roadmap

### ISSUE THREAD

**Issue by albshin** [albshin/teamrpi.club#1]
This is a roadmap for the development of teamrpi.club, the [API backend](https://github.com/albshin/weathermachine), and the [Discord bot](https://github.com/albshin/tutescrew) which also communicates with the API.

Any goals in the roadmap are subject to change.

___

### All
- [ ] User Accounts
  - [ ] **Frontend**: Login Page
  - [ ] **Backend**: Setup database to hold account data
- [ ] Pick-up game tracking
  - [ ] **Frontend**: Stats Page
  - [ ] **Backend**: Setup database to hold pug stat data

### teamrpi.club
- [ ] Events Page
- [ ] Media Page
